// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SmartWr.Ipos.Core.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sp_GetCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sp_GetCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221708546_Sp_GetCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
