// <auto-generated />
namespace SmartWr.Ipos.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IposV2extraFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IposV2extraFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201604081520538_IposV2 extraFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
