// <auto-generated />
namespace Ipos.Sync.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SpoilEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpoilEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281321353_SpoilEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
