// <auto-generated />
namespace Ipos.Sync.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sp_UpdateSyncSpoil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sp_UpdateSyncSpoil));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021037132_Sp_UpdateSyncSpoil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
